openapi: 3.0.1
info:
  title: Favorite News API
  description: This is a sample Spring Boot RESTful service using springdoc-openapi
    and OpenAPI 3.
servers:
  - url: http://localhost:8080
    description: Generated server url
paths:
  "/api/favorites/{id}":
    get:
      tags:
        - favorite-news-controller
      operationId: getFavoriteById
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: OK
          content:
            "*/*":
              schema:
                "$ref": "#/components/schemas/FavoriteNews"
    put:
      tags:
        - favorite-news-controller
      operationId: updateFavorite
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/FavoriteNews"
        required: true
      responses:
        '200':
          description: OK
          content:
            "*/*":
              schema:
                "$ref": "#/components/schemas/FavoriteNews"
    delete:
      tags:
        - favorite-news-controller
      operationId: deleteFavorite
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: OK
  "/api/favorites":
    get:
      tags:
        - favorite-news-controller
      operationId: getAllFavorites
      responses:
        '200':
          description: OK
          content:
            "*/*":
              schema:
                type: array
                items:
                  "$ref": "#/components/schemas/FavoriteNews"
    post:
      tags:
        - favorite-news-controller
      operationId: createFavorite
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/FavoriteNews"
        required: true
      responses:
        '200':
          description: OK
          content:
            "*/*":
              schema:
                type: object
  "/api/favorites/search":
    get:
      tags:
        - favorite-news-controller
      operationId: searchFavoritesByTitle
      parameters:
        - name: title
          in: query
          required: true
          schema:
            type: string
        - name: pageable
          in: query
          required: true
          schema:
            "$ref": "#/components/schemas/Pageable"
      responses:
        '200':
          description: OK
          content:
            "*/*":
              schema:
                "$ref": "#/components/schemas/PageFavoriteNews"
  "/api/favorites/last10":
    get:
      tags:
        - favorite-news-controller
      operationId: getLast10Favorites
      responses:
        '200':
          description: OK
          content:
            "*/*":
              schema:
                type: array
                items:
                  "$ref": "#/components/schemas/FavoriteNews"
components:
  schemas:
    FavoriteNews:
      required:
        - content
        - news_site
        - summary
        - title
        - url
      type: object
      properties:
        id:
          type: integer
          format: int64
        title:
          maxLength: 255
          minLength: 0
          type: string
        content:
          type: string
        summary:
          type: string
        imageUrl:
          type: string
        news_site:
          type: string
        savedAt:
          type: string
        url:
          type: string
    Pageable:
      type: object
      properties:
        page:
          minimum: 0
          type: integer
          format: int32
        size:
          minimum: 1
          type: integer
          format: int32
        sort:
          type: array
          items:
            type: string
    PageFavoriteNews:
      type: object
      properties:
        totalPages:
          type: integer
          format: int32
        totalElements:
          type: integer
          format: int64
        first:
          type: boolean
        last:
          type: boolean
        size:
          type: integer
          format: int32
        content:
          type: array
          items:
            "$ref": "#/components/schemas/FavoriteNews"
        number:
          type: integer
          format: int32
        sort:
          "$ref": "#/components/schemas/SortObject"
        pageable:
          "$ref": "#/components/schemas/PageableObject"
        numberOfElements:
          type: integer
          format: int32
        empty:
          type: boolean
    PageableObject:
      type: object
      properties:
        offset:
          type: integer
          format: int64
        sort:
          "$ref": "#/components/schemas/SortObject"
        paged:
          type: boolean
        unpaged:
          type: boolean
        pageNumber:
          type: integer
          format: int32
        pageSize:
          type: integer
          format: int32
    SortObject:
      type: object
      properties:
        empty:
          type: boolean
        unsorted:
          type: boolean
        sorted:
          type: boolean
